# ansible n1 -m file -a "path=/home/centos/n1_dir state=directory"
---
- name: Update n1
  hosts: n1

  tasks:
  - name: create directory
    file:
      name: /home/centos/new_dir
      state: directory
...
