
---
- name: Update n1
  hosts: n1

  tasks:
  - name: create directory
    file:
      path: /home/centos/new_dir
      state: directory

  - name: create directory
    file:
      path: /home/centos/new_dir_1
      state: directory    
      
- name: Update n2
  hosts: n2

  tasks:
  - name: create directory
    file:
      path: /home/centos/new_dir_1
      state: directory

  - name: create directory
    file:
      path: /home/centos/new_dir_2
      state: directory
    

- name: Update group1
  hosts: g1

  tasks:
  - name: create directory
    file:
      path: /home/centos/new_dir_group1
      state: directory

  - name: create directory
    file:
      path: /home/centos/new_dir_group2
      state: directory    

...
